config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  root 'static_pages#home'
  resources :users
  resources :restaurants do
    resource :favorites,    only: [:create, :destroy ]
  end
  resources :comments,      only: [:create, :destroy]
  resources :notifications, only: :index
  resources :categories, except: [:new, :show]
  resources :boards
  resources :board_comments, only: [:create, :destroy]
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  get    :favorites,     to: 'favorites#index'
  get    '/auth/:provider/callback' => 'users#omniauth'
  post   :'/guest',      to: 'guest_sessions#create' 
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :board
  validates  :user_id,  presence: true
  validates  :board_id, presence: true
  validates  :content,  presence: true, length: { maximum: 1000 }
end

app/controllers/board_comments_controller.rb
class BoardCommentsController < ApplicationController
  before_action :logged_in_user

  def create
    @board = Board.find(params[:board_id])
    @board_comment = @board.board_comments.build(user_id: current_user.id,
                                                 content: params[:board_comment][:content])
    if !@board.nil? && @board_comment.save
      flash[:success] = "コメントを追加しました！"
    else
      flash[:danger] = "空のコメントは投稿できません。"
    end
    redirect_to request.referrer || root_url
  end

  def destroy
    @board_comment = BoardComment.find(params[:id])
    @board = @board_comment.board
    if current_user.id == @board_comment.user_id || current_user.admin?
      @board_comment.destroy
      flash[:success] = "コメントを削除しました"
    end
    redirect_to board_url(@board)
  end
end

app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

app/views/board_comments/_board_comment.html.erb
<% board_comment_user = User.find(board_comment.user_id) %>
<li id="board_comment-<%= board_comment.id %>">
  <div class="row">
    <div class="col-md-3">
      <span class="user"><%= link_to board_comment_user.name, board_comment_user %></span>
    </div>
    <div class="col-md-7">
      <span class="comment"><%= board_comment.content %></span>
    </div>
    <div class="col-md-2">
      <span class="comment-create-at"><%= board_comment.created_at.strftime('%Y/%m/%d') %></span>
      <% if logged_in? %>
        <% if current_user.id == board_comment.user_id || admin? %>
          <%= link_to "削除", board_comment_path(board_comment), method: :delete,
                                      data: { confirm: "本当に削除しますか？" } %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/board_comments/_feed_board_comments.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="title-comment">コメント</h3>
  </div>
</div>
<% if @board_comments.any? %>
  <ul class="comments">
    <%= render @board_comments %>
  </ul>
<% end %>

app/views/board_comments/_new.html.erb
<div class="comment_form">
  <%= form_for(@board_comment) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= hidden_field_tag :board_id, @board.id %>
    <div class="row">
      <div class="col-md-8 col-md-offset-1">
        <div class="field">
          <%= f.text_area :content, placeholder: "コメントを追加..." %>
        </div>
      </div>
      <div class="col-md-3">
        <%= f.submit "コメント", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>