config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  root 'static_pages#home'
  resources :users
  resources :restaurants do
    resource :favorites,    only: [:create, :destroy ]
  end
  resources :comments,      only: [:create, :destroy]
  resources :notifications, only: :index
  resources :categories, except: [:new, :show]
  resources :boards
  resources :board_comments, only: [:create, :destroy]
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  get    :favorites,     to: 'favorites#index'
  get    '/auth/:provider/callback' => 'users#omniauth'
  post   :'/guest',      to: 'guest_sessions#create' 
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates  :user_id, presence: true
  validates  :restaurant_id, presence: true
  validates  :from_user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user

  def index
    # current_userに対する通知の集合を取得
    @notifications = current_user.notifications
    # 一度indexページを開いたら、ユーザーの「通知フラグ」を削除
    current_user.update_attribute(:notification, false)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% user = User.find(notification.from_user_id) %>
<% restaurant = Restaurant.find(notification.restaurant_id) %>
<li id="notification-<%= notification.id %>">
  <div>
    <% if notification %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message"><%= link_to user.name, user_path(user) %>さんからコメントがあります。
      「<%= notification.content %>」</p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <% if restaurant.images? %>
        <%= link_to((image_tag restaurant.images[0].thumb200.url), restaurant_path(restaurant), class: "image-size-small") %>
      <% end %>
    </div>
    <div class="col-md-8">
      <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
      <p><%= restaurant.description %></p>
    </div>
  </div>
</li>

app/views/notifications/index.html.erb
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3>　通知一覧</h3>
      </div>
    </div>
    <% if @notifications.present? %>
      <ol class="notifications">
        <%= render @notifications %>
      </ol>
    <% end %>
  </div>
</div>