config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  root 'static_pages#home'
  resources :users
  resources :restaurants do
    resource :favorites,    only: [:create, :destroy ]
  end
  resources :comments,      only: [:create, :destroy]
  resources :notifications, only: :index
  resources :categories, except: [:new, :show]
  resources :boards
  resources :board_comments, only: [:create, :destroy]
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  get    :favorites,     to: 'favorites#index'
  get    '/auth/:provider/callback' => 'users#omniauth'
  post   :'/guest',      to: 'guest_sessions#create' 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants,   dependent: :destroy
  has_many :favorites,     dependent: :destroy
  has_many :notifications, dependent: :destroy
  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Restaurant.all
  end

  def favorite(restaurant)
    Favorite.create!(user_id: id, restaurant_id: restaurant.id)
  end

  def unfavorite(restaurant)
    Favorite.find_by(user_id: id, restaurant_id: restaurant.id).destroy
  end

  def favorite?(restaurant)
    !Favorite.find_by(user_id: id, restaurant_id: restaurant.id).nil?
  end

  def self.from_omniauth(response)
      User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
        u.name = response[:info][:name]
        u.email = response[:info][:email]
        u.password = SecureRandom.hex(16)
      end
  end

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ポートフォリオへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def omniauth # log users in with omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      log_in user
      flash[:success] = "ポートフォリオへようこそ！"
      redirect_to user_path(user)
    else
      flash[:danger] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      @user.destroy
      flash[:success] = "ユーザーの削除に成功しました"
      redirect_to users_url
    elsif current_user?(@user)
      @user.destroy
      flash[:success] = "自分のアカウントを削除しました"
      redirect_to root_url
    else
      flash[:danger] = "他人のアカウントは削除できません"
      redirect_to root_url
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :sex, :check_in,
                                   :uid, :provider)
    end

    def user_params_update
      params.require(:user).permit(:name, :email, :sex, :check_in)
    end

    def correct_user
      @user = User.find(params[:id])
      if !current_user?(@user)
        flash[:danger] = "このページへはアクセスできません"
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80, cl: "gravatar")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: cl)
  end

  def admin?
    current_user.admin?
  end
end

app/views/users/_favorite.html.erb
<%= link_to restaurant_favorites_path(@restaurant.id),
            method: :post,
            class: 'like',
            remote: true do %>
  <div class="like-btn-like"><i class="fa fa-heart"></i> お気に入りに登録する</div>
<% end %>

app/views/users/_favorite_form.html.erb
<div id="favorite-<%= @restaurant.id %>">
  <% if !current_user.nil? && current_user.favorite?(@restaurant) %>
    <%= render 'users/unfavorite' %>
  <% else %>
    <%= render 'users/favorite' %>
  <% end %>
</div>

app/views/users/_unfavorite.html.erb
<%= link_to restaurant_favorites_path(@restaurant.id),
            method: :delete,
            class: 'unlike',
            remote: true do %>
  <div class="like-btn-unlike"><i class="fa fa-heart"></i> お気に入りを解除</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if (current_user.admin? && current_user != user) || (!current_user.admin? && current_user == user) %>
    | <%= link_to "削除", user_path(user), method: :delete,
                                  data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
        <div class="gravatar_edit">
          <%= gravatar_for(@user, size: 40) %>
          <%= @user.name %>
          <a href="http://gravatar.com/emails" target="_blank">プロフィール写真を変更</a>
        </div>
        <div class = 'form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control', id: 'user_email' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :sex %>
          <%= f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {}, class: 'form-control', id: 'user_sex' %>
        </div>
        <div class='form-group'>
          <%= f.label :check_in %>
          <%= f.text_field :check_in, class: 'form-control', id: 'check_in' %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <%= link_to "アカウントを削除する", user_path(@user), method: :delete,
                                    data: { confirm: "本当にこのアカウントを削除してよろしいですか？" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<div id="fh5co-portfolio">
  <div class="container">
    <h1>ユーザー一覧</h1>
    <%= will_paginate %>
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<div id="fh5co-portfolio">
  <div class="container">
    <h1>ユーザー登録</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with model: @user, local: true do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class='form-group'>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
          </div>
          <div class='form-group'>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
          </div>
          <div class='form-group'>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
          </div>
          <div class='form-group'>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation' %>
          </div>
          <div class = 'form-group'>
            <%= f.label :sex %>
            <%= f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {}, class: 'form-control', id: 'user_sex' %>
          </div>
          <div class='form-group'>
            <%= f.label :check_in %>
            <%= f.text_field :check_in, class: 'form-control', id: 'check_in' %>
          </div>
        <%= f.submit nil, class: 'btn btn-primary' %>
        <% end %>
        <p class="sign-in-or">もしくは...</p>
        <%= button_to "Googleアカウントで登録する", '/auth/google', class: 'btn btn-google' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "プロフィール") %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row profile">
      <div class="col-md-9">
        <h3 class="title-profile">プロフィール</h3>
        <div class="row">
          <div class="col-md-4">
            <div class="user-picture-box">
              <%= gravatar_for @user, size: 120, cl: "gravatar user-picture" %>
            </div>
          </div>
          <div class="col-md-8">
            <h4 class="show-user-name"><%= @user.name %></h4>　<%= @user.sex %>
            <% if current_user == @user %>
              <div class="account-edit"><%= link_to "プロフィール編集", edit_user_path(@user) %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>