config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  root 'static_pages#home'
  resources :users
  resources :restaurants do
    resource :favorites,    only: [:create, :destroy ]
  end
  resources :comments,      only: [:create, :destroy]
  resources :notifications, only: :index
  resources :categories, except: [:new, :show]
  resources :boards
  resources :board_comments, only: [:create, :destroy]
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  get    :favorites,     to: 'favorites#index'
  get    '/auth/:provider/callback' => 'users#omniauth'
  post   :'/guest',      to: 'guest_sessions#create' 
end

app/views/layouts/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 matoba taiki</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_js.html.erb
<!-- jQuery -->
<%= javascript_include_tag('jquery.min') %>
<!-- jQuery Easing -->
<%= javascript_include_tag('jquery.easing.1.3') %>
<!-- Bootstrap -->
<%= javascript_include_tag('bootstrap.min') %>
<!-- Waypoints -->
<%= javascript_include_tag('jquery.waypoints.min') %>
<!-- Flexslider -->
<%= javascript_include_tag('jquery.flexslider-min') %>
<!-- Main -->
<%= javascript_include_tag('main') %>
<!-- Custom -->
<%= javascript_include_tag('custom') %>
<%= javascript_include_tag('googlemap') %>

app/views/layouts/_navigation.html.erb
<nav class="fh5co-nav navbar-fixed-top" role="navigation">
  <div class="top-menu">
    <div class="container">
      <div class="row">
        <div class="col-xs-2">
          <div id="fh5co-logo">
            <%= link_to image_tag("/images/tabeGoo!_logo.png", :alt => "たべGoo!-logo"), root_url, id: 'logo' %>
          </div>
        </div>
        <div class="col-xs-10 text-right menu-1">
          <ul>
            <% if logged_in? %>
              <% if admin? %>
                <li><%= link_to "新しいお店の登録", new_restaurant_path %></li>
              <% end %>
              <li class="header-link">
                <%= link_to restaurants_path do %>
                  <span class="fas fa-store-alt"></span> <span>お店</span>
                <% end %>
              </li>
              <% if admin? %>
                <% if current_user.notification == true %>
                  <li class="new_notification header-link">
                <% else %>
                  <li class="no_notification header-link">
                <% end %>
                <%= link_to notifications_path do %>
                  <span class="fas fa-bell"></span> <span>通知</span>
                <% end %>
                </li>
              <% end %>
              <li class="header-link">
                <%= link_to boards_path do %>
                  <span class="fas fa-id-badge"></span> <span>掲示板</span>
                <% end %>
              </li>
              <li class="header-link">
                <%= link_to favorites_path do %>
                  <span class="fas fa-heart"></span> <span>お気に入り</span>
                <% end %>
              </li>
              <li class="has-dropdown">
                <%= link_to current_user do %>
                  <span class="fas fa-user-cog"></span>
                <% end %>
                <ul class="dropdown">
                  <li><%= link_to 'プロフィール', current_user %></li>
                  <li><%= link_to 'ユーザー一覧', users_path %></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li class="header-link">
                <%= link_to restaurants_path do %>
                  <span class="fas fa-store-alt"></span> <span>お店</span>
                <% end %>
              </li>
              <li class="header-link">
                <%= link_to boards_path do %>
                  <span class="fas fa-id-badge"></span> <span>掲示板</span>
                <% end %>
              </li>
              <li class="header-link">
                <%= link_to signup_path do %><span class="fas fa-user-plus"></span> <span>ユーザー登録</span><% end %>
              </li>
              <li class="header-link btn-cta">
                <%= link_to login_path do %><span> ログイン</span><% end %>
              </li>
              <li class="header-link btn-cta">
                <%= link_to guest_path, method: :post do %><span> ゲストログイン</span><% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="IZA浅草ゲストハウスマネージャーがゲストハウス周辺のお勧めごはん屋さんをお勧めするサービスです。ガイドブックに載っている観光地化しているレストランよりも、よりディープな浅草をご紹介します！掲示板でこれから一緒にご飯を食べに行く人を募集するのも楽しいでしょう！" />
<meta name="keywords" content="たべゴー, 晩ご飯, 居酒屋, 浅草" />
<link rel="shortcut icon" href="/images/favicon.ico">

<!-- Facebook and Twitter integration -->
<meta property="og:title" content=""/>
<meta property="og:image" content=""/>
<meta property="og:url" content=""/>
<meta property="og:site_name" content=""/>
<meta property="og:description" content=""/>
<meta name="twitter:title" content="" />
<meta name="twitter:image" content="" />
<meta name="twitter:url" content="" />
<meta name="twitter:card" content="" />

<link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet">

<%= include_gon %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"] %>"　type="text/javascript"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script async defer src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="fh5co-loader"></div>
    <div id="page">
      <%= render 'layouts/navigation' %>
      <div id="fh5co-wireframe">
        <div class="container">
          <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <div class="gototop js-top">
      <a href="#" class="js-gotop"><i class="fas fa-arrow-up"></i></a>
    </div>
    <%= render 'layouts/js' %>
  </body>
</html>